import All
private import codeql.shared.LanguageBase

module LanguageBase implements LanguageBaseSig<Location> {
  import codeql.js.base.FacadeAst::JS

  /**
   * Holds if a language-specific synthetic node with the given `tag` should be synthesized as a child of `node`.
   *
   * This is in addition to the synthetic nodes generated by the shared base library.
   */
  predicate synthesizeNode(AstNode node, string tag) {
    node instanceof AugmentedAssignmentExpression and tag = "binary-operator"
    or
    node instanceof ForInStatement and tag = "loop-header"
    or
    exists(ForStatement stmt | node = stmt |
      // Add placeholders for optional parts of the `for` statement.
      // Note that the intializer is not optional as it will default to being an empty statement.
      not exists(stmt.getCondition(0)) and
      tag = "empty-condition"
      or
      not exists(stmt.getIncrement()) and
      tag = "empty-increment"
    )
    or
    node instanceof ImportOrExportStatement and
    tag = "imported-module"
  }

  /**
   * Holds if `node` should be included in the CFG.
   *
   * Should not include synthetic nodes. Those are manually wired up in the CFG layer.
   */
  predicate needsCfg(AstNode node) {
    node instanceof Expression
    or
    node instanceof Statement
    or
    node instanceof Program
    or
    node instanceof VariableDeclarator
    or
    node instanceof SequenceExpression // TODO: this should be an Expression. Fix in tree-sitter grammar
  }

  /**
   * Holds if `node` is a CFG scope boundary.
   */
  predicate isCfgScope(AstNode node) {
    node instanceof Program
    or
    node instanceof FunctionExpression
    or
    node instanceof FunctionDeclaration
    or
    node instanceof MethodDefinition
    or
    node instanceof ArrowFunction
    or
    node instanceof GeneratorFunction
    or
    node instanceof GeneratorFunctionDeclaration
  }

  /**
   * Holds if `node` appears in a position where it is written to and not read from.
   *
   * For example, this holds for the target of an assignment (`x = e`) but not for a compound assignment (`x += e`)
   * which is considered an impure l-value position.
   */
  predicate isInPureLValuePosition(AstNode node) {
    node = any(AssignmentExpression e).getLeft()
    or
    node = any(VariableDeclarator v).getName()
    or
    node = any(ForInStatement e).getLeft()
    or
    node = any(PairPattern p).getValue()
    or
    node = any(ArrayPattern p).getChild(_) and not node instanceof RestPattern
    or
    node = any(AssignmentPattern p).getLeft()
    or
    node = any(RestPattern p).getChild()
    or
    node instanceof ShorthandPropertyIdentifierPattern
    // TODO: parentheses
  }

  /**
   * Holds if `node` appears in a position where it is both read from and written to.
   *
   * Concretely, this holds for the target of a compound assignment (`x += e`) or update expression (`x++`).
   */
  predicate isInImpureLValuePosition(AstNode node) {
    node = any(AugmentedAssignmentExpression e).getLeft()
    or
    node = any(UpdateExpression e).getArgument()
    // TODO: parentheses
  }

  /**
   * Holds if `node` appears in a context where it will be evaluated as a condition.
   */
  predicate isCondition(AstNode node) {
    node = any(IfStatement s).getCondition()
    or
    node = any(WhileStatement s).getCondition()
    or
    node = any(DoStatement s).getCondition()
    or
    exists(TernaryExpression expr |
      node = expr.getCondition()
      or
      isCondition(expr) and
      node = [expr.getConsequence(), expr.getAlternative()]
    )
    or
    exists(UnaryExpression unary |
      unary.getOperator() = "!" and
      isCondition(unary) and
      node = unary.getArgument()
    )
    or
    exists(BinaryExpression binary | binary.getOperator() = ["&&", "||", "??"] |
      node = binary.getLeft()
      or
      isCondition(binary) and
      node = binary.getRight()
    )
    or
    exists(AugmentedAssignmentExpression expr | expr.getOperator() = ["&&=", "||=", "??="] |
      node = expr.getLeft()
      or
      isCondition(expr) and
      node = expr.getRight()
    )
    or
    exists(ParenthesizedExpression expr |
      isCondition(expr) and
      node = expr.getChild()
    )
    or
    exists(SequenceExpression expr |
      isCondition(expr) and
      node = max(int i | | expr.getChild(i) order by i)
    )
    or
    // The `x` in `x?.foo` is checked for nullness
    node = any(OptionalChainExpression expr).getBase()
  }

  /**
   * Holds if node appears in a position where it is written to, and the incoming value is interpreted as a condition for a branch.
   *
   * This is a rare situation. In JavaScript, it holds for destructuring patterns with a default value, since the default expression is conditionally executed based on the incoming value.
   */
  predicate isConditionInLValue(AstNode node) {
    node instanceof AssignmentPattern // pattern with a default value
  }

  /**
   * Holds if `node` represents a call.
   */
  predicate isCall(AstNode node) { node instanceof CallExpression }
}

private module Base = MakeLanguageBase<Location, LanguageBase>;

import Base
