import All
private import codeql.shared.LanguageBase

module LanguageBase implements LanguageBaseSig<Location> {
  import codeql.js.base.GeneratedAst::JS

  /**
   * Holds if a language-specific synthetic node with the given `tag` should be synthesized as a child of `node`.
   *
   * This is in addition to the synthetic nodes generated by the shared layer.
   */
  predicate synthesizeNode(AstNode node, string tag) {
    node instanceof AugmentedAssignmentExpression and tag = "binary-operator"
  }

  /**
   * Holds if `node` should be included in the CFG.
   *
   * Should not include synthetic nodes. Those are manually wired up in the CFG layer.
   */
  predicate needsCfg(AstNode node) {
    node instanceof Expression
    or
    node instanceof Statement
    or
    node instanceof Program
  }

  /**
   * Holds if `node` appears in a position where it is written to and not read from.
   *
   * For example, this holds for the target of an assignment (`x = e`) but not for a compound assignment (`x += e`)
   * which is considered an impure l-value position.
   */
  predicate isInPureLValuePosition(AstNode node) {
    node = any(AssignmentExpression e).getLeft()
    or
    exists(VariableDeclarator v |
      exists(v.getValue()) and
      node = v.getName()
    )
    or
    node = any(ForInStatement e).getLeft()
    or
    node = any(PairPattern p).getValue()
    or
    node = any(ArrayPattern p).getChild(_) and not node instanceof RestPattern
    or
    node = any(AssignmentPattern p).getLeft()
    or
    node = any(RestPattern p).getChild()
    // TODO: parentheses
  }

  /**
   * Holds if `node` appears in a position where it is both read from and written to.
   *
   * Concretely, this holds for the target of a compound assignment (`x += e`) or update expression (`x++`).
   */
  predicate isInImpureLValuePosition(AstNode node) {
    node = any(AugmentedAssignmentExpression e).getLeft()
    or
    node = any(UpdateExpression e).getArgument()
    // TODO: parentheses
  }

  /**
   * Holds if `node` appears in a context where it will be evaluated as a condition.
   */
  predicate isCondition(AstNode node) {
    node = any(IfStatement s).getCondition()
    or
    node = any(WhileStatement s).getCondition()
    or
    node = any(DoStatement s).getCondition()
    or
    node = any(TernaryExpression e).getCondition()
    or
    exists(UnaryExpression unary |
      unary.getOperator() = "!" and
      node = unary.getArgument()
    )
    or
    exists(BinaryExpression binary |
      binary.getOperator() = ["&&", "||", "??"] and
      node = binary.getLeft()
    )
    or
    exists(AugmentedAssignmentExpression expr |
      expr.getOperator() = ["&&=", "||=", "??="] and
      node = expr.getLeft()
    )
    or
    // The `x` in `x?.foo` needs to be checked
    node = any(OptionalChainExpression expr).getBase()
  }

  /**
   * Holds if node appears in a position where it is written to, and the incoming value is interpreted as a condition for a branch.
   *
   * This is a rare situation. In JavaScript, it holds for destructuring patterns with a default value, since the default expression is conditionally executed based on the incoming value.
   */
  predicate isConditionInLValue(AstNode node) {
    node instanceof AssignmentPattern // pattern with a default value
  }
}

import MakeLanguageBase<Location, LanguageBase>
