/**
 * The "base" layer contains code that is shared with the post-processing upgrade script (PostProcessing.ql).
 *
 * It should be kept as small as possible, while facilitating code reuse between the main CodeQL libraries and the post-processing script.
 *
 * This file shold re-export everything in the base layer.
 *
 * Note: It is not possible to import arbitrary files here, since upgrades currently can't import anything.
 * We special-case support for importing the files in the "base" layer by inlining them in the generated
 * upgrade script.
 */

private import codeql.util.Location

signature module LanguageBaseSig<LocationSig Location> {
  class AstNode {
    AstNode getParent();

    Location getLocation();

    string toString();

    SyntheticNode getSyntheticChildNode(string tag);
  }

  class Token extends AstNode;

  class SyntheticNode extends AstNode {
    string getTag();
  }

  /**
   * Holds if `node` appears in a context where it will be evaluated as a condition.
   */
  predicate isCondition(AstNode node);

  /**
   * Holds if `node` appears in a parameter position or in an assignment-like context where it is written to and not read from.
   *
   * Typically, this would hold for the target of an assignment (`x = e`) but not for a compound assignment (`x += e`)
   * because the compound assignment also reads from it (which is considered an impure l-value position).
   */
  predicate isInPureLValuePosition(AstNode node);

  /**
   * Holds if `node` appears in an assignment-like context where it is both read from and written to.
   *
   * Typically this would hold for the target of a compound assignment (`x += e`) or update expression (`x++`).
   */
  predicate isInImpureLValuePosition(AstNode node);

  /**
   * Holds if `node` appears in a position where it is written to, and the incoming value is interpreted as a condition
   * for a branch.
   *
   * This is a rare situation. In JavaScript, it holds for destructuring patterns with a default value, since the default
   * expression is conditionally executed based on the incoming value.
   */
  predicate isConditionInLValue(AstNode node);

  /**
   * Holds if `node` should be included in the CFG.
   *
   * Should not include synthetic nodes. Those are manually wired up in the CFG layer.
   */
  predicate needsCfg(AstNode node);

  /**
   * Holds if `node` is a CFG scope boundary.
   */
  predicate isCallable(AstNode node);

  /**
   * Holds if a language-specific synthetic node with the given `tag` should be synthesized as a child of `node`.
   *
   * This is in addition to the synthetic nodes generated by the shared layer.
   */
  predicate synthesizeNode(AstNode node, string tag);

  /**
   * Holds if `node` may perform a call.
   */
  predicate isCall(AstNode node);
}

module MakeLanguageBase<LocationSig Location, LanguageBaseSig<Location> Base> {
  private import Base

  predicate isInPureLValuePosition = Base::isInPureLValuePosition/1;

  predicate isCondition = Base::isCondition/1;

  /**
   * Holds if `node` appears in left-hand position relative to an assignment or in a parameter position.
   */
  predicate isInLValuePosition(AstNode node) {
    isInPureLValuePosition(node)
    or
    isInImpureLValuePosition(node)
  }

  /**
   * Gets the node acting as a junction for values being assigned to the given `node`, which appears in left-hand position of some form of assignment or in a parameter position.
   *
   * The L-value node decouples two orthogonal concerns:
   * - When handling an assignment-like operator, the assigned value should be made to flow into the L-value node, without regard to what kind of L-value it is.
   * - When handling a form of left-hand value, the L-value node should be taken as the "incoming" value, without regard to what context the left-hand value appears in.
   *
   * This helps avoids an N^2 case explosion that would typically arise if these concerns are not properly decoupled.
   */
  AstNode getLValueNode(AstNode node) {
    isInLValuePosition(node) and result = node.getSyntheticChildNode("lvalue")
  }

  SyntheticNode getLValueEndNode(AstNode node) {
    isInLValuePosition(node) and result = node.getSyntheticChildNode("lvalue-end")
  }

  SyntheticNode getTrueOutcomeNode(AstNode node) {
    isCondition(node) and result = node.getSyntheticChildNode("condition-true")
  }

  SyntheticNode getFalseOutcomeNode(AstNode node) {
    isCondition(node) and result = node.getSyntheticChildNode("condition-false")
  }

  SyntheticNode getConditionalOutcomeNode(AstNode node, boolean branch) {
    isCondition(node) and result = node.getSyntheticChildNode("condition-" + branch)
  }

  SyntheticNode getCfgEntryPoint(AstNode node) {
    isCallable(node) and result = node.getSyntheticChildNode("cfg-entry-point")
  }

  SyntheticNode getCfgExitPoint(AstNode node) {
    isCallable(node) and result = node.getSyntheticChildNode("cfg-exit-point")
  }

  SyntheticNode getCfgBegin(AstNode node) { result = node.getSyntheticChildNode("cfg-begin") }

  SyntheticNode getParameterObjectNode(AstNode node) {
    isCallable(node) and result = node.getSyntheticChildNode("parameter-object")
  }

  SyntheticNode getArgumentObjectNode(AstNode node) {
    isCall(node) and result = node.getSyntheticChildNode("argument-object")
  }

  /** Gets the node representing values returned from the given call or callable. */
  SyntheticNode getReturnValueNode(AstNode node) {
    (isCallable(node) or isCall(node)) and
    result = node.getSyntheticChildNode("return-value")
  }

  /** Gets the node representing exceptions thrown by the given call or callable. */
  SyntheticNode getExceptionalReturnValueNode(AstNode node) {
    (isCallable(node) or isCall(node)) and
    result = node.getSyntheticChildNode("return-exception")
  }
}

/**
 * Provides code needed by the post-processing upgrade script to synthesize nodes.
 */
module MakePostProcessor<LocationSig Location, LanguageBaseSig<Location> Base> {
  private import Base

  predicate shouldSynthesize(AstNode node, string tag) {
    Base::synthesizeNode(node, tag)
    or
    (
      isInPureLValuePosition(node)
      or
      isInImpureLValuePosition(node)
    ) and
    tag = ["lvalue", "lvalue-end"]
    or
    isCondition(node) and tag = ["condition-true", "condition-false"]
    or
    isConditionInLValue(node) and tag = ["lvalue-true", "lvalue-false"]
    or
    needsCfg(node) and
    (
      not node instanceof Token
      or
      (isInPureLValuePosition(node) or isInImpureLValuePosition(node)) // TODO: maybe just handle parameters specially
    ) and
    tag = "cfg-begin"
    or
    isCallable(node) and
    tag = ["cfg-entry-point", "cfg-exit-point", "parameter-object"]
    or
    isCall(node) and
    tag = ["argument-object"]
    or
    (isCallable(node) or isCall(node)) and
    tag = ["return-value", "return-exception"]
  }

  class AstNode = Base::AstNode;
}
