#!/bin/sh

set -eu

echo "CODEQL_EXTRACTOR_LEAN_TRAP_DIR = $CODEQL_EXTRACTOR_LEAN_TRAP_DIR"
echo "CODEQL_EXTRACTOR_LEAN_WIP_DATABASE = $CODEQL_EXTRACTOR_LEAN_WIP_DATABASE"

"${CODEQL_EXTRACTOR_LEAN_ROOT}/tools/${CODEQL_PLATFORM}/extractor" \
        extract \
        --file-list "$1" \
        --source-archive-dir "$CODEQL_EXTRACTOR_LEAN_SOURCE_ARCHIVE_DIR" \
        --output-dir "$CODEQL_EXTRACTOR_LEAN_TRAP_DIR"
