private import javascript

private class Sinks extends ModelInput::SinkModelCsv {
  override predicate row(string row) {
    row =
      [
        "@google-cloud/spanner/build/src/batch-transaction;BatchTransaction;Member[createQueryPartitions].Argument[0];sql-injection", //
        "@google-cloud/spanner/build/src/transaction;Dml;Member[runUpdate].Argument[0];sql-injection", //
        "@google-cloud/spanner/build/src/transaction;Statement;Member[sql];sql-injection", //
        "@google-cloud/spanner;Database;Member[run,runPartitionedUpdate,runStream].Argument[0];sql-injection", //
        "@google-cloud/spanner;PartitionedDml;Member[runUpdate].Argument[0];sql-injection", //
        "@google-cloud/spanner;Snapshot;Member[run,runStream].Argument[0];sql-injection", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.IStatement;Member[sql];sql-injection", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.Statement;Member[sql];sql-injection", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteSqlRequest;Member[sql];sql-injection", //
        "@google-cloud/spanner;protos.google.spanner.v1.IExecuteSqlRequest;Member[sql];sql-injection", //
        "@google-cloud/spanner;protos.google.spanner.v1.IPartitionQueryRequest;Member[sql];sql-injection", //
        "@google-cloud/spanner;protos.google.spanner.v1.PartitionQueryRequest;Member[sql];sql-injection", //
        "@google-cloud/spanner;protos.google.spanner.v1.Spanner;Member[executeSql,executeStreamingSql,partitionQuery].Argument[0];sql-injection", //
        "@google-cloud/spanner;v1.SpannerClient;Member[executeSql,executeStreamingSql,partitionQuery].Argument[0];sql-injection", //
      ]
  }
}

private class Types extends ModelInput::TypeModelCsv {
  override predicate row(string row) {
    row =
      [
        "@google-cloud/spanner/batch-transaction;BatchTransaction;@google-cloud/spanner/batch-transaction;BatchTransactionStatic;Instance", //
        "@google-cloud/spanner/batch-transaction;BatchTransaction;@google-cloud/spanner/database;CreateBatchTransactionCallback;Argument[1]", //
        "@google-cloud/spanner/batch-transaction;BatchTransaction;@google-cloud/spanner;Database;Member[batchTransaction].ReturnValue", //
        "@google-cloud/spanner/batch-transaction;BatchTransactionStatic;@google-cloud/spanner/batch-transaction;;Member[BatchTransaction]", //
        "@google-cloud/spanner/batch-transaction;TransactionIdentifier;@google-cloud/spanner/batch-transaction;BatchTransaction;Member[identifier].ReturnValue", //
        "@google-cloud/spanner/batch-transaction;TransactionIdentifier;@google-cloud/spanner;Database;Member[batchTransaction].Argument[0]", //
        "@google-cloud/spanner/database;BatchCreateSessionsCallback;@google-cloud/spanner;Database;Member[batchCreateSessions].Argument[1]", //
        "@google-cloud/spanner/database;CreateBatchTransactionCallback;@google-cloud/spanner;Database;Member[createBatchTransaction].Argument[0,1]", //
        "@google-cloud/spanner/database;CreateSessionCallback;@google-cloud/spanner;Database;Member[createSession].Argument[0,1]", //
        "@google-cloud/spanner/database;DatabaseCallback;@google-cloud/spanner;Database;Member[get].Argument[0,1]", //
        "@google-cloud/spanner/database;GetSessionsCallback;@google-cloud/spanner;Database;Member[getSessions].Argument[0,1]", //
        "@google-cloud/spanner/database;GetSessionsResponse;@google-cloud/spanner;Database;Member[getSessions].ReturnValue.Awaited", //
        "@google-cloud/spanner/database;GetSnapshotCallback;@google-cloud/spanner;Database;Member[getSnapshot].Argument[0,1]", //
        "@google-cloud/spanner/database;GetTransactionCallback;@google-cloud/spanner;Database;Member[getTransaction].Argument[0]", //
        "@google-cloud/spanner/database;PoolRequestCallback;@google-cloud/spanner;Database;Member[makePooledRequest_].Argument[1]", //
        "@google-cloud/spanner/database;RestoreDatabaseCallback;@google-cloud/spanner;Database;Member[restore].Argument[1,2]", //
        "@google-cloud/spanner/database;SessionPoolConstructor;@google-cloud/spanner;DatabaseStatic;Argument[2]", //
        "@google-cloud/spanner/database;SessionPoolConstructor;@google-cloud/spanner;Instance;Member[database].Argument[1]", //
        "@google-cloud/spanner/instance;CreateDatabaseCallback;@google-cloud/spanner;Instance;Member[createDatabase].Argument[1,2]", //
        "@google-cloud/spanner/instance;CreateDatabaseOptions;@google-cloud/spanner;Instance;Member[createDatabase].Argument[1]", //
        "@google-cloud/spanner/instance;CreateInstanceCallback;@google-cloud/spanner;Spanner;Member[createInstance].Argument[2]", //
        "@google-cloud/spanner/instance;GetDatabasesCallback;@google-cloud/spanner;Instance;Member[getDatabases].Argument[0,1]", //
        "@google-cloud/spanner/instance;GetDatabasesResponse;@google-cloud/spanner;Instance;Member[getDatabases].ReturnValue.Awaited", //
        "@google-cloud/spanner/instance;GetInstanceCallback;@google-cloud/spanner;Instance;Member[get].Argument[0,1]", //
        "@google-cloud/spanner/session-pool;GetReadSessionCallback;@google-cloud/spanner/session-pool;SessionPoolInterface;Member[getReadSession].Argument[0]", //
        "@google-cloud/spanner/session-pool;GetReadSessionCallback;@google-cloud/spanner;SessionPool;Member[getReadSession].Argument[0]", //
        "@google-cloud/spanner/session-pool;GetWriteSessionCallback;@google-cloud/spanner/session-pool;SessionPoolInterface;Member[getWriteSession].Argument[0]", //
        "@google-cloud/spanner/session-pool;GetWriteSessionCallback;@google-cloud/spanner;SessionPool;Member[getWriteSession].Argument[0]", //
        "@google-cloud/spanner/session-pool;SessionInventory;@google-cloud/spanner;SessionPool;Member[_inventory]", //
        "@google-cloud/spanner/session-pool;SessionPoolInterface;@google-cloud/spanner/database;SessionPoolConstructor;Instance", //
        "@google-cloud/spanner/session-pool;SessionPoolInterface;@google-cloud/spanner;Database;Member[pool_]", //
        "@google-cloud/spanner/session-pool;SessionPoolInterface;@google-cloud/spanner;SessionPool;", //
        "@google-cloud/spanner/table;CreateTableCallback;@google-cloud/spanner;Database;Member[createTable].Argument[1,2]", //
        "@google-cloud/spanner/table;CreateTableCallback;@google-cloud/spanner;Table;Member[create].Argument[1,2]", //
        "@google-cloud/spanner/transaction-runner;AsyncRunTransactionCallback;@google-cloud/spanner/transaction-runner;AsyncTransactionRunner;Member[runFn]", //
        "@google-cloud/spanner/transaction-runner;AsyncRunTransactionCallback;@google-cloud/spanner/transaction-runner;AsyncTransactionRunnerStatic;Argument[2]", //
        "@google-cloud/spanner/transaction-runner;AsyncRunTransactionCallback;@google-cloud/spanner;Database;Member[runTransactionAsync].Argument[0,1]", //
        "@google-cloud/spanner/transaction-runner;AsyncTransactionRunner;@google-cloud/spanner/transaction-runner;AsyncTransactionRunnerStatic;Instance", //
        "@google-cloud/spanner/transaction-runner;AsyncTransactionRunnerStatic;@google-cloud/spanner/transaction-runner;;Member[AsyncTransactionRunner]", //
        "@google-cloud/spanner/transaction-runner;RunTransactionCallback;@google-cloud/spanner/transaction-runner;TransactionRunner;Member[runFn]", //
        "@google-cloud/spanner/transaction-runner;RunTransactionCallback;@google-cloud/spanner/transaction-runner;TransactionRunnerStatic;Argument[2]", //
        "@google-cloud/spanner/transaction-runner;RunTransactionCallback;@google-cloud/spanner;Database;Member[runTransaction].Argument[0,1]", //
        "@google-cloud/spanner/transaction-runner;Runner;@google-cloud/spanner/transaction-runner;AsyncTransactionRunner;", //
        "@google-cloud/spanner/transaction-runner;Runner;@google-cloud/spanner/transaction-runner;RunnerStatic;Instance", //
        "@google-cloud/spanner/transaction-runner;Runner;@google-cloud/spanner/transaction-runner;TransactionRunner;", //
        "@google-cloud/spanner/transaction-runner;RunnerStatic;@google-cloud/spanner/transaction-runner;;Member[Runner]", //
        "@google-cloud/spanner/transaction-runner;TransactionRunner;@google-cloud/spanner/transaction-runner;TransactionRunnerStatic;Instance", //
        "@google-cloud/spanner/transaction-runner;TransactionRunnerStatic;@google-cloud/spanner/transaction-runner;;Member[TransactionRunner]", //
        "@google-cloud/spanner/transaction;Dml;@google-cloud/spanner/transaction;DmlStatic;Instance", //
        "@google-cloud/spanner/transaction;Dml;@google-cloud/spanner;PartitionedDml;", //
        "@google-cloud/spanner/transaction;Dml;@google-cloud/spanner;Transaction;", //
        "@google-cloud/spanner/transaction;DmlStatic;@google-cloud/spanner/transaction;;Member[Dml]", //
        "@google-cloud/spanner;BackupStatic;@google-cloud/spanner/backup;;Member[Backup]", //
        "@google-cloud/spanner;BackupStatic;@google-cloud/spanner/backup;BackupStatic;", //
        "@google-cloud/spanner;BackupStatic;@google-cloud/spanner;;Member[Backup]", //
        "@google-cloud/spanner;Database;@google-cloud/spanner/database;Database;", //
        "@google-cloud/spanner;Database;@google-cloud/spanner/database;DatabaseCallback;Argument[1]", //
        "@google-cloud/spanner;Database;@google-cloud/spanner/database;RestoreDatabaseCallback;Argument[1]", //
        "@google-cloud/spanner;Database;@google-cloud/spanner/database;SessionPoolConstructor;Argument[0]", //
        "@google-cloud/spanner;Database;@google-cloud/spanner/instance;CreateDatabaseCallback;Argument[1]", //
        "@google-cloud/spanner;Database;@google-cloud/spanner;DatabaseStatic;Instance", //
        "@google-cloud/spanner;Database;@google-cloud/spanner;Instance;Member[database].ReturnValue", //
        "@google-cloud/spanner;Database;@google-cloud/spanner;SessionPool;Member[database]", //
        "@google-cloud/spanner;Database;@google-cloud/spanner;SessionPoolStatic;Argument[0]", //
        "@google-cloud/spanner;Database;@google-cloud/spanner;SessionStatic;Argument[0]", //
        "@google-cloud/spanner;Database;@google-cloud/spanner;Table;Member[database]", //
        "@google-cloud/spanner;Database;@google-cloud/spanner;TableStatic;Argument[0]", //
        "@google-cloud/spanner;DatabaseStatic;@google-cloud/spanner/database;;Member[Database]", //
        "@google-cloud/spanner;DatabaseStatic;@google-cloud/spanner/database;DatabaseStatic;", //
        "@google-cloud/spanner;DatabaseStatic;@google-cloud/spanner;;Member[Database]", //
        "@google-cloud/spanner;GetInstancesCallback;@google-cloud/spanner/build/src;GetInstancesCallback;", //
        "@google-cloud/spanner;GetInstancesCallback;@google-cloud/spanner;Spanner;Member[getInstances].Argument[0,1]", //
        "@google-cloud/spanner;GetInstancesResponse;@google-cloud/spanner/build/src;GetInstancesResponse;", //
        "@google-cloud/spanner;GetInstancesResponse;@google-cloud/spanner;Spanner;Member[getInstances].ReturnValue.Awaited", //
        "@google-cloud/spanner;Instance;@google-cloud/spanner/instance;CreateInstanceCallback;Argument[1]", //
        "@google-cloud/spanner;Instance;@google-cloud/spanner/instance;GetInstanceCallback;Argument[1]", //
        "@google-cloud/spanner;Instance;@google-cloud/spanner/instance;Instance;", //
        "@google-cloud/spanner;Instance;@google-cloud/spanner;BackupStatic;Argument[0]", //
        "@google-cloud/spanner;Instance;@google-cloud/spanner;DatabaseStatic;Argument[0]", //
        "@google-cloud/spanner;Instance;@google-cloud/spanner;GetInstancesCallback;Argument[1].ArrayElement", //
        "@google-cloud/spanner;Instance;@google-cloud/spanner;InstanceStatic;Instance", //
        "@google-cloud/spanner;Instance;@google-cloud/spanner;Spanner;Member[instance].ReturnValue", //
        "@google-cloud/spanner;InstanceStatic;@google-cloud/spanner/instance;;Member[Instance]", //
        "@google-cloud/spanner;InstanceStatic;@google-cloud/spanner/instance;InstanceStatic;", //
        "@google-cloud/spanner;InstanceStatic;@google-cloud/spanner;;Member[Instance]", //
        "@google-cloud/spanner;PartitionedDml;@google-cloud/spanner/transaction;PartitionedDml;", //
        "@google-cloud/spanner;PartitionedDml;@google-cloud/spanner;PartitionedDmlStatic;Instance", //
        "@google-cloud/spanner;PartitionedDml;@google-cloud/spanner;Session;Member[partitionedDml].ReturnValue", //
        "@google-cloud/spanner;PartitionedDmlStatic;@google-cloud/spanner/transaction;;Member[PartitionedDml]", //
        "@google-cloud/spanner;PartitionedDmlStatic;@google-cloud/spanner/transaction;PartitionedDmlStatic;", //
        "@google-cloud/spanner;PartitionedDmlStatic;@google-cloud/spanner;;Member[PartitionedDml]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner/batch-transaction;TransactionIdentifier;Member[session]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner/database;BatchCreateSessionsCallback;Argument[1].ArrayElement", //
        "@google-cloud/spanner;Session;@google-cloud/spanner/database;CreateSessionCallback;Argument[1]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner/session-pool;GetReadSessionCallback;Argument[1]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner/session-pool;GetWriteSessionCallback;Argument[1]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner/session-pool;SessionPoolInterface;Member[release].Argument[0]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner/session;Session;", //
        "@google-cloud/spanner;Session;@google-cloud/spanner/transaction-runner;AsyncTransactionRunnerStatic;Argument[0]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner/transaction-runner;Runner;Member[session]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner/transaction-runner;RunnerStatic;Argument[0]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner/transaction-runner;TransactionRunnerStatic;Argument[0]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;Database;Member[_runPartitionedUpdate].Argument[0]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;Database;Member[makePooledRequest_].ReturnValue.Awaited", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;Database;Member[session].ReturnValue", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;PartitionedDmlStatic;Argument[0]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;SessionPool;Member[_acquire,_getSession].ReturnValue.Awaited", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;SessionPool;Member[_borrow,_destroy,_isValidSession,_ping,_prepareTransaction,_release,release].Argument[0]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;SessionPool;Member[_borrowFrom,_borrowNextAvailableSession].ReturnValue", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;SessionPool;Member[_getIdleSessions].ReturnValue.ArrayElement", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;SessionStatic;Instance", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;Snapshot;Member[session]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;SnapshotStatic;Argument[0]", //
        "@google-cloud/spanner;Session;@google-cloud/spanner;TransactionStatic;Argument[0]", //
        "@google-cloud/spanner;SessionPool;@google-cloud/spanner/instance;CreateDatabaseOptions;Member[poolCtor]", //
        "@google-cloud/spanner;SessionPool;@google-cloud/spanner/session-pool;SessionPool;", //
        "@google-cloud/spanner;SessionPool;@google-cloud/spanner;SessionPoolStatic;Instance", //
        "@google-cloud/spanner;SessionPoolStatic;@google-cloud/spanner/session-pool;;Member[SessionPool]", //
        "@google-cloud/spanner;SessionPoolStatic;@google-cloud/spanner/session-pool;SessionPoolStatic;", //
        "@google-cloud/spanner;SessionPoolStatic;@google-cloud/spanner;;Member[SessionPool]", //
        "@google-cloud/spanner;SessionStatic;@google-cloud/spanner/session;;Member[Session]", //
        "@google-cloud/spanner;SessionStatic;@google-cloud/spanner/session;SessionStatic;", //
        "@google-cloud/spanner;SessionStatic;@google-cloud/spanner;;Member[Session]", //
        "@google-cloud/spanner;Snapshot;@google-cloud/spanner/batch-transaction;BatchTransaction;", //
        "@google-cloud/spanner;Snapshot;@google-cloud/spanner/database;GetSnapshotCallback;Argument[1]", //
        "@google-cloud/spanner;Snapshot;@google-cloud/spanner/transaction;Dml;", //
        "@google-cloud/spanner;Snapshot;@google-cloud/spanner/transaction;Snapshot;", //
        "@google-cloud/spanner;Snapshot;@google-cloud/spanner;Session;Member[snapshot].ReturnValue", //
        "@google-cloud/spanner;Snapshot;@google-cloud/spanner;SnapshotStatic;Instance", //
        "@google-cloud/spanner;SnapshotStatic;@google-cloud/spanner/transaction;;Member[Snapshot]", //
        "@google-cloud/spanner;SnapshotStatic;@google-cloud/spanner/transaction;SnapshotStatic;", //
        "@google-cloud/spanner;SnapshotStatic;@google-cloud/spanner;;Member[Snapshot]", //
        "@google-cloud/spanner;Spanner;@google-cloud/spanner;InstanceStatic;Argument[0]", //
        "@google-cloud/spanner;Spanner;@google-cloud/spanner;SpannerStatic;Instance", //
        "@google-cloud/spanner;SpannerStatic;@google-cloud/spanner;;Member[Spanner]", //
        "@google-cloud/spanner;Table;@google-cloud/spanner/table;CreateTableCallback;Argument[1]", //
        "@google-cloud/spanner;Table;@google-cloud/spanner/table;Table;", //
        "@google-cloud/spanner;Table;@google-cloud/spanner;Database;Member[table].ReturnValue", //
        "@google-cloud/spanner;Table;@google-cloud/spanner;TableStatic;Instance", //
        "@google-cloud/spanner;TableStatic;@google-cloud/spanner/table;;Member[Table]", //
        "@google-cloud/spanner;TableStatic;@google-cloud/spanner/table;TableStatic;", //
        "@google-cloud/spanner;TableStatic;@google-cloud/spanner;;Member[Table]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/database;GetTransactionCallback;Argument[1]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/session-pool;GetWriteSessionCallback;Argument[2]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/transaction-runner;AsyncRunTransactionCallback;Argument[0]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/transaction-runner;AsyncTransactionRunner;Member[_run].Argument[0]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/transaction-runner;AsyncTransactionRunnerStatic;Argument[1]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/transaction-runner;RunTransactionCallback;Argument[1]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/transaction-runner;Runner;Member[_run].Argument[0]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/transaction-runner;Runner;Member[getTransaction].ReturnValue.Awaited", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/transaction-runner;Runner;Member[transaction]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/transaction-runner;RunnerStatic;Argument[1]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/transaction-runner;TransactionRunner;Member[_run].Argument[0]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/transaction-runner;TransactionRunnerStatic;Argument[1]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner/transaction;Transaction;", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner;Session;Member[transaction].ReturnValue", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner;Session;Member[txn]", //
        "@google-cloud/spanner;Transaction;@google-cloud/spanner;TransactionStatic;Instance", //
        "@google-cloud/spanner;TransactionStatic;@google-cloud/spanner/transaction;;Member[Transaction]", //
        "@google-cloud/spanner;TransactionStatic;@google-cloud/spanner/transaction;TransactionStatic;", //
        "@google-cloud/spanner;TransactionStatic;@google-cloud/spanner;;Member[Transaction]", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.IStatement;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.Statement;", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.IStatement;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.StatementStatic;Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.IStatement;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.StatementStatic;Member[create,encode,encodeDelimited].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.IStatement;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest;Member[statements].ArrayElement", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.IStatement;@google-cloud/spanner;protos.google.spanner.v1.IExecuteBatchDmlRequest;Member[statements].ArrayElement", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.Statement;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.StatementStatic;Instance", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.Statement;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.StatementStatic;Member[create,decode,decodeDelimited,fromObject].ReturnValue", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.Statement;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.StatementStatic;Member[toObject].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest.StatementStatic;@google-cloud/spanner;;Member[protos].Member[google].Member[spanner].Member[v1].Member[ExecuteBatchDmlRequest].Member[Statement]", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequestStatic;Instance", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequestStatic;Member[create,decode,decodeDelimited,fromObject].ReturnValue", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequestStatic;Member[toObject].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequestStatic;@google-cloud/spanner;;Member[protos].Member[google].Member[spanner].Member[v1].Member[ExecuteBatchDmlRequest]", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteSqlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteSqlRequestStatic;Instance", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteSqlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteSqlRequestStatic;Member[create,decode,decodeDelimited,fromObject].ReturnValue", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteSqlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteSqlRequestStatic;Member[toObject].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.ExecuteSqlRequestStatic;@google-cloud/spanner;;Member[protos].Member[google].Member[spanner].Member[v1].Member[ExecuteSqlRequest]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IExecuteBatchDmlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequest;", //
        "@google-cloud/spanner;protos.google.spanner.v1.IExecuteBatchDmlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequestStatic;Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IExecuteBatchDmlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteBatchDmlRequestStatic;Member[create,encode,encodeDelimited].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IExecuteBatchDmlRequest;@google-cloud/spanner;protos.google.spanner.v1.Spanner;Member[executeBatchDml].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IExecuteBatchDmlRequest;@google-cloud/spanner;v1.SpannerClient;Member[executeBatchDml].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IExecuteSqlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteSqlRequest;", //
        "@google-cloud/spanner;protos.google.spanner.v1.IExecuteSqlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteSqlRequestStatic;Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IExecuteSqlRequest;@google-cloud/spanner;protos.google.spanner.v1.ExecuteSqlRequestStatic;Member[create,encode,encodeDelimited].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IExecuteSqlRequest;@google-cloud/spanner;protos.google.spanner.v1.Spanner;Member[executeSql,executeStreamingSql].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IExecuteSqlRequest;@google-cloud/spanner;v1.SpannerClient;Member[executeSql,executeStreamingSql].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IPartitionQueryRequest;@google-cloud/spanner;protos.google.spanner.v1.PartitionQueryRequest;", //
        "@google-cloud/spanner;protos.google.spanner.v1.IPartitionQueryRequest;@google-cloud/spanner;protos.google.spanner.v1.PartitionQueryRequestStatic;Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IPartitionQueryRequest;@google-cloud/spanner;protos.google.spanner.v1.PartitionQueryRequestStatic;Member[create,encode,encodeDelimited].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IPartitionQueryRequest;@google-cloud/spanner;protos.google.spanner.v1.Spanner;Member[partitionQuery].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.IPartitionQueryRequest;@google-cloud/spanner;v1.SpannerClient;Member[partitionQuery].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.PartitionQueryRequest;@google-cloud/spanner;protos.google.spanner.v1.PartitionQueryRequestStatic;Instance", //
        "@google-cloud/spanner;protos.google.spanner.v1.PartitionQueryRequest;@google-cloud/spanner;protos.google.spanner.v1.PartitionQueryRequestStatic;Member[create,decode,decodeDelimited,fromObject].ReturnValue", //
        "@google-cloud/spanner;protos.google.spanner.v1.PartitionQueryRequest;@google-cloud/spanner;protos.google.spanner.v1.PartitionQueryRequestStatic;Member[toObject].Argument[0]", //
        "@google-cloud/spanner;protos.google.spanner.v1.PartitionQueryRequestStatic;@google-cloud/spanner;;Member[protos].Member[google].Member[spanner].Member[v1].Member[PartitionQueryRequest]", //
        "@google-cloud/spanner;protos.google.spanner.v1.Spanner;@google-cloud/spanner;protos.google.spanner.v1.SpannerStatic;Instance", //
        "@google-cloud/spanner;protos.google.spanner.v1.Spanner;@google-cloud/spanner;protos.google.spanner.v1.SpannerStatic;Member[create].ReturnValue", //
        "@google-cloud/spanner;protos.google.spanner.v1.SpannerStatic;@google-cloud/spanner;;Member[protos].Member[google].Member[spanner].Member[v1].Member[Spanner]", //
        "@google-cloud/spanner;v1.SpannerClient;@google-cloud/spanner/v1/spanner_client;SpannerClient;", //
        "@google-cloud/spanner;v1.SpannerClient;@google-cloud/spanner;v1.SpannerClientStatic;Instance", //
        "@google-cloud/spanner;v1.SpannerClientStatic;@google-cloud/spanner/v1/spanner_client;;Member[SpannerClient]", //
        "@google-cloud/spanner;v1.SpannerClientStatic;@google-cloud/spanner/v1/spanner_client;SpannerClientStatic;", //
        "@google-cloud/spanner;v1.SpannerClientStatic;@google-cloud/spanner;;Member[v1].Member[SpannerClient]", //
      ]
  }
}
